from typing import Dict, Any, Optional

class ImpactEngine:
    def __init__(self):
        # Configurable assumptions for estimations
        self.assumptions = {
            "emission_factor_kg_per_idle_min": 0.015, # kg CO2e per minute of idling per vehicle
            "vehicle_class_distribution": {"car": 0.8, "truck": 0.1, "bus": 0.1},
            "average_vehicle_length_m": 4.5,
            "lane_capacity_veh_per_hr": 1800,
            "free_flow_speed_kmh": 50.0,
            "segment_length_km": 0.5 # Default assumed observed segment length
        }

    def calculate_impact(self, telemetry: Dict[str, Any]) -> Dict[str, Any]:
        """
        Calculates impact metrics based on telemetry.
        Classifies metrics by evidence hierarchy.
        """
        # 1. Observed Metrics
        vehicle_count = telemetry.get("vehicle_count", 0)
        avg_speed_kmh = telemetry.get("average_speed", 0.0)
        
        # 2. Estimated Metrics
        # Estimate queue length
        # Assuming density = count / segment_length, queue = congested vehicles * avg_length
        # Simplistic model: if speed is below threshold, treat as queued
        estimated_queue_m = 0.0
        if avg_speed_kmh < 20.0 and vehicle_count > 0:
            estimated_queue_m = vehicle_count * self.assumptions["average_vehicle_length_m"]
            
        # Estimate delay
        free_flow_speed = self.assumptions["free_flow_speed_kmh"]
        segment_length_km = self.assumptions["segment_length_km"]
        
        estimated_delay_min = 0.0
        if 0 < avg_speed_kmh < free_flow_speed:
            actual_travel_time_min = (segment_length_km / avg_speed_kmh) * 60
            ideal_travel_time_min = (segment_length_km / free_flow_speed) * 60
            estimated_delay_min = max(0.0, actual_travel_time_min - ideal_travel_time_min)
        elif avg_speed_kmh == 0 and vehicle_count > 0:
            # Standstill penalty
            estimated_delay_min = 5.0 # baseline penalty for standstill
            
        total_delay_min = estimated_delay_min * vehicle_count
        
        # Estimate emissions generated by delay/idling
        estimated_emissions_kg = total_delay_min * self.assumptions["emission_factor_kg_per_idle_min"]
        
        metrics = []
        
        # 1. Observed Metrics
        metrics.append({
            "metric": "vehicle_count",
            "value": vehicle_count,
            "unit": "vehicles",
            "evidence_type": "observed",
            "confidence": 1.0,
            "assumptions": {},
            "source": "yolo_tracker"
        })
        
        metrics.append({
            "metric": "average_speed",
            "value": avg_speed_kmh,
            "unit": "km/h",
            "evidence_type": "observed",
            "confidence": 0.95,
            "assumptions": {},
            "source": "optical_flow"
        })
        
        # 2. Estimated Metrics
        metrics.append({
            "metric": "estimated_queue",
            "value": round(estimated_queue_m, 1),
            "unit": "meters",
            "evidence_type": "estimated",
            "confidence": 0.85,
            "assumptions": {"average_vehicle_length_m": self.assumptions["average_vehicle_length_m"]},
            "source": "impact_engine"
        })
        
        metrics.append({
            "metric": "estimated_delay",
            "value": round(estimated_delay_min, 1),
            "unit": "min/vehicle",
            "evidence_type": "estimated",
            "confidence": 0.78,
            "assumptions": {"free_flow_speed_kmh": self.assumptions["free_flow_speed_kmh"]},
            "source": "impact_engine"
        })
        
        metrics.append({
            "metric": "estimated_emissions",
            "value": round(estimated_emissions_kg, 2),
            "unit": "kg_co2e",
            "evidence_type": "estimated",
            "confidence": 0.75,
            "assumptions": {"emission_factor_kg_per_idle_min": self.assumptions["emission_factor_kg_per_idle_min"]},
            "source": "impact_engine"
        })
        
        return {
            "metrics": metrics,
            "summary": {
                "total_delay_min": round(total_delay_min, 1)
            }
        }
        
impact_engine = ImpactEngine()
